# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create scoring matrix based on hamming distance for kmers
#'
#' @param k_len an integer specifying the length of the k-mer
#' @param lambda an integer specifying the lambda for the exponential decay function. Set to NULL to use custom scale function
#' @param unweighted logical, if TRUE returns matrix of all 1s (except N vs N = 0)
#' @param scale_fun R function for scaling hamming distances (default: function(x) 1/(1+x^3))
#' @return NumericMatrix of k-mer similarity scores where element (i,j) represents similarity between k-mer i and k-mer j
#' @export
create_hamming_distance_matrix_cpp <- function(k_len, lambda = 1.0, unweighted = FALSE, scale_fun = NULL) {
    .Call(`_germs_create_hamming_distance_matrix_cpp`, k_len, lambda, unweighted, scale_fun)
}

#' Chops sequence into k-mers
#'
#' @param input_seq a character string
#' @param k_len an integer specifying the length of the k-mer
#'
#' @return character vector of k-mers
#' @export
kmer_chopper <- function(input_seq, k_len) {
    .Call(`_germs_kmer_chopper`, input_seq, k_len)
}

#' Calculates k-mer multivalencies
#'
#' @param input_seq sequence string
#' @param k_len an integer specifying the length of the k-mer
#' @param window_size integer specifying window_size
#' @param hamming_distances the Hamming distance matrix
#' @param positional_distances the positional distance vector
#'
#' @return a vector of k-mer multivalencies
#' @export
calculate_kmer_multivalencies <- function(input_seq, k_len, window_size, hamming_distances, positional_distances) {
    .Call(`_germs_calculate_kmer_multivalencies`, input_seq, k_len, window_size, hamming_distances, positional_distances)
}

#' Get list of k-mer multivalencies
#'
#' @param ins list of ??
#' @param k_len an integer specifying the length of the k-mer
#' @param window_size integer specifying window_size
#' @param hamming_distances the Hamming distance matrix
#' @param positional_distances the positional distance vector
#'
#' @return a list of k-mer multivalencies
#' @export
list_kmer_multivalencies <- function(ins, k_len, window_size, hamming_distances, positional_distances) {
    .Call(`_germs_list_kmer_multivalencies`, ins, k_len, window_size, hamming_distances, positional_distances)
}

#' Calculates sliding mean and pads ends with 0
#'
#' @param iv numeric vector
#' @param ws sliding window size
#'
#' @return numeric vector of sliding means padded with 0
#' @export
calculate_padded_sliding_mean <- function(iv, ws) {
    .Call(`_germs_calculate_padded_sliding_mean`, iv, ws)
}

#' Calculates k-mer multivalencies with tidy output
#'
#' @param input_seq sequence string
#' @param input_seq_name sequence string name (e.g. transcript id)
#' @param k_len an integer specifying the length of the k-mer
#' @param window_size integer specifying window_size
#' @param smoothing size integer specifying smoothingwindow_size
#' @param hamming_distances the Hamming distance matrix
#' @param positional_distances the positional distance vector
#'
#' @return a data frame of k-mer multivalencies
#' @export
calculate_kmer_multivalencies_df <- function(input_seq, input_seq_name, k_len, window_size, smoothing_size, hamming_distances, positional_distances) {
    .Call(`_germs_calculate_kmer_multivalencies_df`, input_seq, input_seq_name, k_len, window_size, smoothing_size, hamming_distances, positional_distances)
}

#' Calculates k-mer multivalencies with tidy output for complete 2d matrix and a positional distance matrix
#'
#' @param input_seq sequence string
#' @param input_seq_name sequence string name (e.g. transcript id)
#' @param k_len an integer specifying the length of the k-mer
#' @param smoothing size integer specifying smoothingwindow_size
#' @param hamming_distances the Hamming distance matrix
#' @param positional_distances the positional distance matrix
#'
#' @return a list with matrix of pairwise k-mer weighted similarities and data frame of k-mer multivalencies summed per position
#' @export
calculate_kmer_pairwise_multivalencies <- function(input_seq, input_seq_name, k_len, smoothing_size, hamming_distances, positional_distances) {
    .Call(`_germs_calculate_kmer_pairwise_multivalencies`, input_seq, input_seq_name, k_len, smoothing_size, hamming_distances, positional_distances)
}

#' Calculates sliding mean
#'
#' @param iv numeric vector
#' @param ws window size
#'
#' @return numeric vector of sliding means
#' @export
calculate_sliding_mean <- function(iv, ws) {
    .Call(`_germs_calculate_sliding_mean`, iv, ws)
}

#' Creates a list of sliding means.
#'
#' @param ins A list of numeric vectors (intended to be from  the list_kmer_multivalencies function).
#' @param window_size An integer specifying the size of the window within which to calculate mean values.
#'
#' @return list of numeric vectors containing the sliding window mean values.
#' @export
list_sliding_means <- function(ins, window_size) {
    .Call(`_germs_list_sliding_means`, ins, window_size)
}

